name: pinterest_clone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  clerk_flutter: ^0.0.14-beta
  clerk_auth: ^0.0.14-beta
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/pinterest_splash_logo.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/pinterest_splash_logo.png
    icon_background_color: "#FFFFFF"

  web: false
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/

